checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  gulp@*:
    dependencies:
      "@types/undertaker": "*"
  redux-thunk@*:
    dependencies:
      "@types/redux": "*"
      redux: "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"

plugins: null

yarnPath: .yarn/releases/yarn-4.5.0.cjs
