checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  gulp@*:
    dependencies:
      "@types/undertaker": "*"
  redux-thunk@*:
    dependencies:
      "@types/redux": "*"
      redux: "*"
  keshi@*:
    peerDependenciesMeta:
      "@types/keshi":
        optional: true
  "@conventional-changelog/git-client@*":
    dependencies:
      conventional-commits-filter: "*"
      conventional-commits-parser: "*"

plugins: null

yarnPath: .yarn/releases/yarn-4.13.0.cjs
