approvedGitRepositories:
  - "**"

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

packageExtensions:
  "@conventional-changelog/git-client@*":
    dependencies:
      conventional-commits-filter: "*"
      conventional-commits-parser: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  gulp@*:
    dependencies:
      "@types/undertaker": "*"
  keshi@*:
    peerDependenciesMeta:
      "@types/keshi":
        optional: true
  redux-thunk@*:
    dependencies:
      "@types/redux": "*"
      redux: "*"

plugins: null

yarnPath: .yarn/releases/yarn-4.14.1.cjs
