export {
  DEFAULT_AUTHOR,
  DEFAULT_DESCRIPTION,
  DEFAULT_LANGUAGE,
  DEFAULT_VERSION,
  DEFAULT_LIB_PATH,
  DEFAULT_STYLE_LANGUAGE,
} from "../defaults";

export const DEFAULT_SOURCE_ROOT = "src/ts";
