export const KEYBOARD_LAYOUT_DEFAULT = [
  "` 1 2 3 4 5 6 7 8 9 0 - = {bksp}",
  "{tab} q w e r t y u i o p [ ] \\",
  "{lock} a s d f g h j k l ; ' {enter}",
  "{shift} z x c v b n m , . / {shift}",
  ".com @ {space}",
];

export const KEYBOARD_LAYOUT_SHIFT = [
  "~ ! @ # $ % ^ & * ( ) _ + {bksp}",
  "{tab} Q W E R T Y U I O P { } |",
  '{lock} A S D F G H J K L : " {enter}',
  "{shift} Z X C V B N M < > ? {shift}",
  ".com @ {space}",
];

/**
 * Default button display labels
 * TODO: Use i18n module for this
 */
export const KEYBOARD_LAYOUT_LABELS_DEFAULT = {
  "{bksp}": "backspace",
  "{enter}": "enter",
  "{shift}": "shift",
  "{shiftleft}": "shift",
  "{shiftright}": "shift",
  "{alt}": "alt",
  "{s}": "shift",
  "{tab}": "tab",
  "{lock}": "caps",
  "{capslock}": "caps",
  "{accept}": "Submit",
  "{space}": " ",
  "{//}": " ",
  "{esc}": "esc",
  "{escape}": "esc",
  "{f1}": "f1",
  "{f2}": "f2",
  "{f3}": "f3",
  "{f4}": "f4",
  "{f5}": "f5",
  "{f6}": "f6",
  "{f7}": "f7",
  "{f8}": "f8",
  "{f9}": "f9",
  "{f10}": "f10",
  "{f11}": "f11",
  "{f12}": "f12",
  "{numpaddivide}": "/",
  "{numlock}": "lock",
  "{arrowup}": "↑",
  "{arrowleft}": "←",
  "{arrowdown}": "↓",
  "{arrowright}": "→",
  "{prtscr}": "print",
  "{scrolllock}": "scroll",
  "{pause}": "pause",
  "{insert}": "ins",
  "{home}": "home",
  "{pageup}": "up",
  "{delete}": "del",
  "{forwarddelete}": "del",
  "{end}": "end",
  "{pagedown}": "down",
  "{numpadmultiply}": "*",
  "{numpadsubtract}": "-",
  "{numpadadd}": "+",
  "{numpadenter}": "enter",
  "{period}": ".",
  "{numpaddecimal}": ".",
  "{numpad0}": "0",
  "{numpad1}": "1",
  "{numpad2}": "2",
  "{numpad3}": "3",
  "{numpad4}": "4",
  "{numpad5}": "5",
  "{numpad6}": "6",
  "{numpad7}": "7",
  "{numpad8}": "8",
  "{numpad9}": "9",
};
