- title: Guide
  url: guide.html
  links: []
- title: Modules
  url: "#collapse"
  collapseable: true
  links:
    - title: Core
      url: "#collapse"
      collapseable: true
      links:
        - title: Install
          url: core.html
        - title: Binders
          url: core-binders.html
        - title: Formatters
          url: core-formatters.html
        - title: Components
          url: core-components.html
    - title: Router
      url: "#collapse"
      collapseable: true
      links:
        - title: Getting Started
          url: router.html
        - title: Lifecycle
          url: router-lifecycle.html
        - title: Transitions
          url: router-transitions.html
        - title: Hooks
          url: router-hooks.html
        - title: Strategies
          url: router-strategies.html
        - title: Recipes
          url: router-recipes.html
        - title: Binders
          url: router-binders.html
        - title: Components
          url: router-components.html
    - title: I18n
      url: i18n.html
      links: []
    - title: Iconset
      url: iconset.html
      links: []
    - title: jQuery
      url: jquery.html
      links: []
    - title: Bootstrap 5
      url: bs5.html
      links: []
    - title: Extras
      url: extras.html
      links: []
    - title: OctoberCMS
      url: octobercms.html
      links: []
