"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var view_binder_1 = require("./view.binder");
exports.viewBinder = view_binder_1.viewBinder;
var view_static_binder_1 = require("./view-static.binder");
exports.viewStaticBinder = view_static_binder_1.viewStaticBinder;
var route_binder_1 = require("./route.binder");
exports.routeBinder = route_binder_1.routeBinder;
var route_class_star_binder_1 = require("./route-class-star.binder");
exports.routeClassStarBinder = route_class_star_binder_1.routeClassStarBinder;
var parent_route_class_star_binder_1 = require("./parent-route-class-star.binder");
exports.parentRouteClassStarBinder = parent_route_class_star_binder_1.parentRouteClassStarBinder;
var route_back_on_star_binder_1 = require("./route-back-on-star.binder");
exports.routeBackOnStarBinder = route_back_on_star_binder_1.routeBackOnStarBinder;
