name: Build
on:
  pull_request:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: |
          yarn --version
          yarn install
      - name: Type check all packages
        run: |
          yarn run check:all
      - name: Build configured workspaces
        run: |
          yarn run build
